
import Header from '../components/Header'
import './globals.css'

export const metadata = {
title: 'Create Next App',
description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
return (
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body className='bg-zinc-950'>
<Header />
<main className='w-screen min-h-fit pt-[60px]  flex flex-col'>
{children}
</main>
</body>
</html>
)
}
